Repository ywmoyue/biliuwp-lite, pull requests merged in 2024-12, with the labels that each got.

#928 分离主题颜色
  src/BiliLite.UWP/App.xaml
  src/BiliLite.UWP/App.xaml.cs
  src/BiliLite.UWP/BiliLite.UWP.csproj
  src/BiliLite.UWP/MainPage.xaml.cs
  src/BiliLite.UWP/Services/ThemeService.cs
  src/BiliLite.UWP/Styles/Breakpoint.xaml
  src/BiliLite.UWP/Styles/Converter.xaml
  src/BiliLite.UWP/Styles/Fonts.xaml
  src/BiliLite.UWP/Themes/Blue.xaml
  src/BiliLite.UWP/Themes/Colors.xaml
  src/BiliLite.UWP/Themes/Default.xaml
  src/BiliLite.UWP/Themes/Pink.xaml
Labels: 已完成, 优化建议

#931 升级至C#最新版本
  src/BiliLite.JSBridge/BiliLite.JSBridge.csproj
  src/BiliLite.UWP/BiliLite.UWP.csproj
Labels: 已完成, 优化建议

#932 #925 #900 调整标签栏样式、支持自定义相关样式
  src/BiliLite.UWP/BiliLite.UWP.csproj
  src/BiliLite.UWP/Controls/PlayerControl.xaml.cs
  src/BiliLite.UWP/Controls/Settings/UISettingsControl.xaml
  src/BiliLite.UWP/Controls/Settings/UISettingsControl.xaml.cs
  src/BiliLite.UWP/Converters/InverseBooleanConverter.cs
  src/BiliLite.UWP/MainPage.xaml
  src/BiliLite.UWP/MainPage.xaml.cs
  src/BiliLite.UWP/Models/Common/SettingConstants.cs
  src/BiliLite.UWP/Pages/LiveDetailPage.xaml.cs
  src/BiliLite.UWP/Pages/SeasonDetailPage.xaml.cs
  src/BiliLite.UWP/Pages/VideoDetailPage.xaml.cs
  src/BiliLite.UWP/Services/FrostMasterDanmakuController.cs
  src/BiliLite.UWP/Services/NsDanmakuController.cs
  src/BiliLite.UWP/Styles/Converter.xaml
  src/BiliLite.UWP/Styles/TabViewStyle.xaml
  src/BiliLite.UWP/ViewModels/Common/MainPageViewModel.cs
Labels: bug, 已完成, 需求

#952 更新sdk19041
  src/BiliLite.UWP/BiliLite.UWP.csproj
Labels: 已完成, 特殊处理

#959 圣诞更新（直播间优化）
  src/BiliLite.UWP/BiliLite.UWP.csproj
  src/BiliLite.UWP/Extensions/TimeExtensions.cs
  src/BiliLite.UWP/Models/Common/Enumerates.cs
  src/BiliLite.UWP/Models/Common/Live/LiveMessageHandleActionsMap.cs
  src/BiliLite.UWP/Models/Common/Live/LiveRoomEmoticon.cs
  src/BiliLite.UWP/Models/Requests/Api/Live/LiveRoomAPI.cs
  src/BiliLite.UWP/Modules/Live/LiveMessage.cs
  src/BiliLite.UWP/Pages/LiveDetailPage.xaml
  src/BiliLite.UWP/Pages/LiveDetailPage.xaml.cs
  src/BiliLite.UWP/ViewModels/Live/LiveRoomViewModel.cs
Labels: bug, 已完成, 需求
