Repository ywmoyue/biliuwp-lite, pull requests merged in 2024-01, with the labels that each got.

#470 修复港澳台番剧播放
  src/BiliLite.UWP/Models/Requests/Api/SeasonApi.cs
Labels: bug, 已完成

#472 修复了从非番剧页打开番剧时产生的错误
  src/BiliLite.UWP/Extensions/BiliExtensions.cs
  src/BiliLite.UWP/Models/Common/Enumerates.cs
  src/BiliLite.UWP/Models/Requests/Api/SeasonApi.cs
Labels: bug, 开发中

#462 美化弹幕栏与优化直播播放以及问题修复
  src/BiliLite.UWP/Extensions/StringExtensions.cs
  src/BiliLite.UWP/Models/Common/Enumerates.cs
  src/BiliLite.UWP/Models/Common/Live/DanmuMsgModel.cs
  src/BiliLite.UWP/Models/Common/Live/GuardBuyMsgModel.cs
  src/BiliLite.UWP/Models/Common/Live/LiveMessageHandleActionsMap.cs
  src/BiliLite.UWP/Modules/Live/LiveMessage.cs
  src/BiliLite.UWP/Pages/LiveDetailPage.xaml
  src/BiliLite.UWP/Pages/LiveDetailPage.xaml.cs
  src/BiliLite.UWP/Pages/UserInfoPage.xaml
  src/BiliLite.UWP/Player/SubPlayers/LiveHlsPlayer.cs
  src/BiliLite.UWP/ViewModels/Live/LiveRoomViewModel.cs
Labels: bug, 已完成, 需求

#475 画面尺寸添加兼容模式，修复部分设备缩放画面黑屏的问题
  src/BiliLite.UWP/Controls/Player.xaml.cs
  src/BiliLite.UWP/Controls/PlayerControl.xaml
  src/BiliLite.UWP/Controls/PlayerControl.xaml.cs
  src/BiliLite.UWP/Player/IBiliPlayer.cs
Labels: bug, 已完成

#480 修复热门页错误，调整元素布局
  src/BiliLite.UWP/Models/Requests/Api/Home/HotApi.cs
  src/BiliLite.UWP/Pages/Home/HotPage.xaml
Labels: bug, 已完成
